### ISSUE TITLE
是否支持自定义添加报告

### ISSUE THREAD

**Issue by imzengyang** [liushilive/HTMLReport#2]
你好，请问下，我使用unittest做selenium的自动化 ，我添加的有截图功能，是否支持将图片添加到测试报告中？

**Comment by liushilive** [comment]
可以的，修改报告模板即可，后期我将加入截图功能。最近比较忙。

**Comment by liushilive** [comment]
@imzengyang  我已经添加好了日志保存图片功能，你更新下试试，看是否合意
